#!/usr/bin/env php

<?php
require __DIR__.'/vendor/autoload.php';

use Shobi\Weatherapp\Weatherapp;

$app      = new Weatherapp();
$location = $argv[1] ?? "london";

try {
    $weather = $app->current($location);
} catch(Exception $e) {
    die("Uh oh... The location " . $location . " doesn't seems to be present in our database");
}

die($weather);
