#!/usr/bin/env php

<?php
require __DIR__.'/vendor/autoload.php';

use Shobi\Weatherapp\Weatherapp;
use Shobi\Weatherapp\Http\Client;
use GuzzleHttp\Exception\ClientException;

$client   = new Client('6723df6a02149f85e517ad8d4836c748'); //token can be kept in some configuration file; maybe in next iteration
$app      = new Weatherapp($client);
$location = $argv[1] ?? "london";

try {
    $weather = $app->current($location);
} catch(ClientException $e) {
    echo "Uh oh... The location " . $location . " doesn't seems to be present in our database" . PHP_EOL;
    exit(1);
}

echo $weather . PHP_EOL;

